version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 5s
        timeout: 3s
        retries: 5

  weatherapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherapp
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - Redis__Connection=redis:6379,abortConnect=false

volumes:
  redis-data: